# Generated by Django 4.2.28 on 2026-03-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_swap_deleted_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='partner_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
