# Generated by Django 5.2.10 on 2026-03-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(choices=[('Pop', 'Pop'), ('Rock', 'Rock'), ('Hip Hop', 'Hip Hop'), ('Jazz', 'Jazz'), ('Classical', 'Classical'), ('Electronic', 'Electronic'), ('Country', 'Country'), ('Unknown', 'Unknown')], default='Unknown', max_length=100),
        ),
    ]
