# Generated by Django 5.2.10 on 2026-03-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0002_fooditem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='category',
            field=models.CharField(choices=[('Meals', 'Meals'), ('Drinks', 'Drinks'), ('Snacks', 'Snacks'), ('Desserts', 'Desserts'), ('General', 'General')], default='General', max_length=100),
        ),
    ]
